### ISSUE TITLE
Issue with jar build

### ISSUE THREAD

**Issue by Schnikonos** [lucidfrontier45/ElasticsearchSink2#1]
Thx a lot for addressing the compatibility issue between ElasticSearch 2.0.0 and Flume!
However I have an issue creating the jar files using gradlew (I attached the logs
[buildLogs.txt](https://github.com/lucidfrontier45/ElasticsearchSink2/files/33723/buildLogs.txt))
Would you be by any chance familiar with this issue ?
(sorry to open this as an issue as it is likely not linked to your dev but to a config error on my part, but I'm pulling my hairs over it, and and I can't seem to find a solution)

**Comment by lucidfrontier45** [comment]
What OS do you use?
I confirmed Ubuntu 12.04 and 14.04 with JDK 1.8 is OK.

Anyway, I included jar in the release page. You can download jar there.
https://github.com/lucidfrontier45/ElasticsearchSink2/releases

**Comment by lucidfrontier45** [comment]
Are you using NFS, SMB or some other network share file system?

Looks gradle have some issue with them.
http://stackoverflow.com/questions/25242268/gradle-copy-job-fails-on-smb-fs-though-file-copied-successfully

Can you try to build in your local file system?

**Comment by Schnikonos** [comment]
Hello,
Thx a lot for your quick reply!
It was indeed just a config issue: build failed with JDK 1.7, but worked flawlessly with JDK 1.8.
Thx and have a good day !
